### ISSUE TITLE
Update readme so others can make use of this tool

### ISSUE THREAD

**Issue by jimboid** [jimboid/openvpn-supervisor#1]
See title

**Comment by raupie** [comment]
Been looking for something like this. Instructions would be great!

**Comment by jimboid** [comment]
I didn't think anyone would use it. I'll type something up to get you going.

**Comment by raupie** [comment]
Thanks. I think I can figure it out without one but a write up would make
it easier. My transmission goes out every now and then. Woud like to avoid
a Cron job for restarting jail on a schedule.
